resource_types:
- name: slack-notifier
  type: docker-image
  source:
    repository: mockersf/concourse-slack-notifier

resources:
- name: repo-dev
  type: git
  source:
    uri: https://github.com/kenojiri/cakephp-sample.git
    branch: develop

- name: cf
  type: cf
  source:
    api: ((cf_api))
    username: ((cf_username))
    password: ((cf_password))
    organization: ((cf_org))
    space: ((cf_space))
    skip_cert_check: true

- name: slack
  type: slack-notifier
  source:
    url: ((slack_webhook_url))

jobs:
- name: unit-test
  plan:
  - put: slack
    params:
      alert_type: started
      message: unit test started
  - get: repo-dev
    trigger: true
  - task: phpunit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: php
          tag: 7.4.3-cli
      inputs:
      - name: repo-dev
      run:
        path: bash
        args:
        - -c
        - |
          set -ex

          apt-get update
          apt-get install -y unzip libicu-dev
          docker-php-ext-configure intl
          docker-php-ext-install intl
          docker-php-ext-configure pdo_mysql
          docker-php-ext-install pdo_mysql

          cd repo-dev
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
          php composer.phar update
          DEBUG=true vendor/bin/phpunit
    on_success:
      put: slack
      params:
        alert_type: started
        message: unit test success. starting to deploy to staging
    on_failure:
      put: slack
      params:
        alert_type: failed 

- name: deploy-staging
  plan:
  - get: repo-dev
    passed:
    - unit-test
    trigger: true
  - put: cf
    params:
      manifest: repo-dev/manifest-staging.yml
    on_success:
      put: slack
      params:
        alert_type: success
    on_failure:
      put: slack
      params:
        alert_type: failed 

